### ISSUE TITLE
ov_augment_plays() create columns without column name

### ISSUE THREAD

**Issue by wehsLai** [openvolley/ovlytics#2]
After run the code
```r
    z %>%
      plays() %>%
      ov_augment_plays(to_add = c("receiving_team", "touch_summaries", "followed", "setters", "winners"))
```

I got three columns without column name
``lag(.data$match_id) %eq% .data$match_id``
``lag(.data$point_id) %eq% .data$point_id``
``(...)``

https://github.com/openvolley/ovlytics/blob/0810bf94e79716dca047689a446e57e63969b6ae/R/augment.R#L38

**Comment by raymondben** [comment]
Whoops!  Thanks @wehsLai , it should be fixed now.

**Comment by raymondben** [comment]
(Found a different but related issue, will re-close this issue when it's fixed)
